/**
 * PSG sound effects for the GBA (M14f).
 *
 * GB Studio compiles every non-.wav sound - .vgm, FX Hammer, and the Play Tone / Beep /
 * Crash events' "legacy" sounds - to gbvm's sfx_player stream: a byte array per effect,
 * plus a mute mask naming the music channels it borrows (`void AT(mask) __mute_mask_X;`).
 * gbavm plays that exact stream on the GBA's Game Boy PSG (src/psg_sfx.cpp), so the eject
 * reuses the GB compile's output rather than compiling the sounds again: it lifts each
 * array and mask out of the compiled `sounds/*.c` files and re-emits them as plain C.
 */

/**
 * Marks a PSG effect's index in the bridge's data symbols. `_<symbol>` for a .wav sound
 * resolves to a DirectSound index; for a PSG effect it resolves to `index | PSG_SFX_FLAG`,
 * so VM_SFX_PLAY can tell the two apart and emit the right op.
 */
export const PSG_SFX_FLAG = 0x100;

export interface PsgSfx {
  symbol: string;
  bytes: number[];
  muteMask: number;
}

const parseCInt = (token: string): number => {
  const t = token.trim();
  const value = /^0b[01]+$/i.test(t)
    ? parseInt(t.slice(2), 2)
    : /^0x[0-9a-f]+$/i.test(t)
      ? parseInt(t.slice(2), 16)
      : /^\d+$/.test(t)
        ? parseInt(t, 10)
        : NaN;
  if (Number.isNaN(value) || value < 0 || value > 0xff) {
    throw new Error(`gbaPsgSfx: "${t}" is not a byte`);
  }
  return value;
};

/** Every effect array in one compiled sound C file, with its mute mask. */
export const parsePsgSfxC = (c: string): PsgSfx[] => {
  const masks = new Map<string, number>();
  for (const m of c.matchAll(
    /void\s+AT\(\s*([^)]+?)\s*\)\s+__mute_mask_(\w+)\s*;/g,
  )) {
    masks.set(m[2], parseCInt(m[1]));
  }
  const effects: PsgSfx[] = [];
  for (const m of c.matchAll(
    /const\s+(?:UINT8|uint8_t)\s+(\w+)\s*\[\]\s*=\s*\{([\s\S]*?)\};/g,
  )) {
    const symbol = m[1];
    const body = m[2].replace(/\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");
    const bytes = body
      .split(",")
      .map((t) => t.trim())
      .filter((t) => t.length > 0)
      .map(parseCInt);
    const muteMask = masks.get(symbol);
    if (muteMask === undefined) {
      throw new Error(`gbaPsgSfx: no mute mask for ${symbol}`);
    }
    effects.push({ symbol, bytes, muteMask });
  }
  return effects;
};

/**
 * All PSG effects in a compiled project's files: every `sounds/*.c` except those of
 * `skipSymbols` (the .wav sounds, which play on DirectSound instead).
 */
export const collectPsgSfx = (
  files: Record<string, string>,
  skipSymbols: Set<string>,
): PsgSfx[] => {
  const effects: PsgSfx[] = [];
  for (const [name, c] of Object.entries(files).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    const m = /^sounds\/(\w+)\.c$/.exec(name);
    if (!m || skipSymbols.has(m[1])) continue;
    effects.push(...parsePsgSfxC(c));
  }
  return effects;
};

/** The effects as one C translation unit for gbavm. */
export const psgSfxC = (effects: PsgSfx[]): string => {
  const hex = (b: number) =>
    `0x${b.toString(16).toUpperCase().padStart(2, "0")}`;
  const arrays = effects.map(({ symbol, bytes, muteMask }) => {
    const rows: string[] = [];
    for (let i = 0; i < bytes.length; i += 16) {
      rows.push(
        `    ${bytes
          .slice(i, i + 16)
          .map(hex)
          .join(", ")},`,
      );
    }
    return `// mute mask ${hex(muteMask)}\nconst uint8_t ${symbol}[] = {\n${rows.join("\n")}\n};\n`;
  });
  return [
    "// Generated by GBA Studio (M14f) - PSG sound effects: gbvm sfx_player streams.",
    "#include <stdint.h>",
    "",
    ...arrays,
  ].join("\n");
};
